use_frameworks!

platform :ios, '8.0'

target 'XMX_NetWorking_Example' do
  pod 'XMX_NetWorking', :path => '../'

  target 'XMX_NetWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
